#Put the App Resource Bundle (.arb) input files
#in ${FLUTTER_PROJECT}/assets/l10n. The .arb provide localization resources for your app.
arb-dir: assets/l10n
#Set the English template as app_en.arb.
template-arb-file: app_en.arb
#Told Flutter to generate localizations in the app_localizations.dart file.
output-localization-file: app_localizations.dart